package com.mehrbodmk.factesimchin.models

enum class Missions {
    GODFATHER_SHOOTS_PLAYER,
    GODFATHER_NATOS_PLAYER,
    BOMBER_BOMBS_PLAYER,
    DETECTIVE_ACKNOWLEDGES_PLAYER,
    DOCTOR_HEALS_PLAYER,
    SNIPER_HEALS_PLAYER,
    GUNNER_GIVES_BULLET,
    DETONATOR_DETONATES,
}