package com.mehrbodmk.factesimchin.models

enum class Missions {
    GODFATHER_SHOOTS_PLAYER,
    GODFATHER_NATOS_PLAYER,
    GODFATHER_TALKS_WITH_ROLED_CITIZEN,
    BOMBER_BOMBS_PLAYER,
    DETECTIVE_ACKNOWLEDGES_PLAYER,
    DOCTOR_HEALS_PLAYER,
    SNIPER_SHOOTS_PLAYER,
    GUNNER_GIVES_DUMMY_BULLET,
    GUNNER_GIVES_WAR_BULLET,
    DETONATOR_DETONATES,
    BARTENDER_GIVES_DRINK,
    DR_LECTER_SAVES_MAFIA,
}