package com.mehrbodmk.factesimchin.models

enum class NightStepsInOrder {
    SLEEP_EVERYONE,

    WAKE_ALL_MAFIAS,
    GODFATHER_SHOW_LIKE,
    GODFATHER_DOES_WHAT,
    BOMBER_SHOW_LIKE,
    BOMBER_BOMBS_WHO,
    SLEEP_MAFIA,
    WAKE_DOCTOR,
    DOCTOR_SAVES_WHO,
    SLEEP_DOCTOR,
    WAKE_DETECTIVE,
    DETECTIVE_ACKNOWLEDGES_WHO,
    SLEEP_DETECTIVE,
    WAKE_SNIPER,
    SNIPER_SHOOTS_WHO,
    SLEEP_SNIPER,
    WAKE_GUNNER,
    GUNNER_GIVES_BULLETS_TO_WHO,
    SLEEP_GUNNER,
    WAKE_DETONATOR,
    DETONATOR_DETONATES_WHO,
    SLEEP_DETONATOR,

    WAKE_UP_EVERYONE,

    DISPLAY_EVENTS,
}